// Code generated by protoc-gen-go. DO NOT EDIT.
// source: elalmirante-agent.proto

package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DeployRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Ref                  string   `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeployRequest) Reset()         { *m = DeployRequest{} }
func (m *DeployRequest) String() string { return proto.CompactTextString(m) }
func (*DeployRequest) ProtoMessage()    {}
func (*DeployRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_elalmirante_agent_1111210c51473b88, []int{0}
}
func (m *DeployRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployRequest.Unmarshal(m, b)
}
func (m *DeployRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployRequest.Marshal(b, m, deterministic)
}
func (dst *DeployRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployRequest.Merge(dst, src)
}
func (m *DeployRequest) XXX_Size() int {
	return xxx_messageInfo_DeployRequest.Size(m)
}
func (m *DeployRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeployRequest proto.InternalMessageInfo

func (m *DeployRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DeployRequest) GetRef() string {
	if m != nil {
		return m.Ref
	}
	return ""
}

type DeployResponse struct {
	Output               string   `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeployResponse) Reset()         { *m = DeployResponse{} }
func (m *DeployResponse) String() string { return proto.CompactTextString(m) }
func (*DeployResponse) ProtoMessage()    {}
func (*DeployResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_elalmirante_agent_1111210c51473b88, []int{1}
}
func (m *DeployResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployResponse.Unmarshal(m, b)
}
func (m *DeployResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployResponse.Marshal(b, m, deterministic)
}
func (dst *DeployResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployResponse.Merge(dst, src)
}
func (m *DeployResponse) XXX_Size() int {
	return xxx_messageInfo_DeployResponse.Size(m)
}
func (m *DeployResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeployResponse proto.InternalMessageInfo

func (m *DeployResponse) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

func (m *DeployResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*DeployRequest)(nil), "rpc.DeployRequest")
	proto.RegisterType((*DeployResponse)(nil), "rpc.DeployResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DeployServiceClient is the client API for DeployService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DeployServiceClient interface {
	Deploy(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (*DeployResponse, error)
}

type deployServiceClient struct {
	cc *grpc.ClientConn
}

func NewDeployServiceClient(cc *grpc.ClientConn) DeployServiceClient {
	return &deployServiceClient{cc}
}

func (c *deployServiceClient) Deploy(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (*DeployResponse, error) {
	out := new(DeployResponse)
	err := c.cc.Invoke(ctx, "/rpc.DeployService/Deploy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeployServiceServer is the server API for DeployService service.
type DeployServiceServer interface {
	Deploy(context.Context, *DeployRequest) (*DeployResponse, error)
}

func RegisterDeployServiceServer(s *grpc.Server, srv DeployServiceServer) {
	s.RegisterService(&_DeployService_serviceDesc, srv)
}

func _DeployService_Deploy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployServiceServer).Deploy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.DeployService/Deploy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployServiceServer).Deploy(ctx, req.(*DeployRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DeployService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.DeployService",
	HandlerType: (*DeployServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Deploy",
			Handler:    _DeployService_Deploy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "elalmirante-agent.proto",
}

func init() {
	proto.RegisterFile("elalmirante-agent.proto", fileDescriptor_elalmirante_agent_1111210c51473b88)
}

var fileDescriptor_elalmirante_agent_1111210c51473b88 = []byte{
	// 173 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0x41, 0x0b, 0x82, 0x40,
	0x10, 0x85, 0x31, 0x49, 0x68, 0xa0, 0x88, 0x29, 0x4a, 0x3a, 0x85, 0xa7, 0x2e, 0x09, 0xe5, 0xbd,
	0x43, 0xf4, 0x0b, 0xec, 0x17, 0x98, 0x3c, 0x43, 0x32, 0x77, 0x1b, 0xd7, 0xc0, 0x7f, 0x1f, 0xb6,
	0xeb, 0xc1, 0xdb, 0xbc, 0x0f, 0x3e, 0xde, 0x3c, 0xda, 0xa2, 0xca, 0xaa, 0x77, 0x29, 0x59, 0x6d,
	0x70, 0xcc, 0x9e, 0xa8, 0x4d, 0xac, 0x45, 0x19, 0xc5, 0xbe, 0xe8, 0x3c, 0x4a, 0x68, 0x7e, 0x83,
	0xae, 0x54, 0x97, 0xe2, 0xd3, 0xa2, 0x31, 0xbc, 0x24, 0xff, 0x85, 0x2e, 0xf4, 0xf6, 0xde, 0x61,
	0x96, 0xf6, 0x67, 0x4f, 0x04, 0x45, 0x38, 0xb1, 0x44, 0x50, 0x44, 0x17, 0x5a, 0x0c, 0x52, 0xa3,
	0x55, 0xdd, 0x80, 0x37, 0x14, 0xa8, 0xd6, 0xe8, 0xd6, 0x38, 0xd1, 0x25, 0x5e, 0xd3, 0x14, 0x22,
	0x4a, 0x9c, 0x6d, 0xc3, 0xf9, 0x3a, 0x94, 0xde, 0x21, 0xdf, 0x32, 0x07, 0x9f, 0x28, 0xb0, 0x80,
	0x39, 0x16, 0x9d, 0xc7, 0xa3, 0x97, 0x76, 0xab, 0x11, 0xb3, 0x8d, 0x8f, 0xe0, 0x3f, 0x22, 0xf9,
	0x05, 0x00, 0x00, 0xff, 0xff, 0x85, 0x1c, 0x5b, 0x59, 0xdf, 0x00, 0x00, 0x00,
}
